### PR TITLE
Adding script for bit.ly

### PR DESCRIPTION
**Pull request by galanggg**
moving into draft pr

### CODE REVIEW

**Review by empeje — APPROVED** [review]

**Comment by empeje** [comment]
also please refer to the PR number #21 for options implementation @galanggg

**Comment by empeje** [comment]
Are you still interested in continuing this PR @galanggg?

**Comment by galanggg** [comment]
yup i'm still interested to try implement this and i'm working on it, are you in rush ? @empeje

**Comment by empeje** [comment]
No rush @galanggg, I just want to make sure what is the status. Also please let us know if you have any issue.

**Comment by empeje** [comment]
close in lieu of #33

**Pull request closed without merging**
