### PR TITLE
Feature/short io provider

### PR DESCRIPTION
**Pull request by yuliefas**
reff:
Implement short.io #1

new default icon (kulkul icon) and add options shortener provider handler

Screen Shot 2020-10-19 at 15 08 29

now ngecilin have custom domain by short.io

Screen Shot 2020-10-19 at 00 19 29

### CODE REVIEW

**Comment by empeje** [comment]
If the provider is Short.io, can we get the list of the domain in the pop-up UI instead of the options menu?

Please refer to https://developers.short.io/docs/getting-a-list-of-domains

**Comment by yuliefas** [comment]
Oh i see i missed it @empeje
Ok let me give update tomorrow or asap

**Comment by empeje** [comment]
Thanks, mas @yuliefas, also we need to bump the version when merging to master, so I'd like to including it in our upcoming version `1.1.0`, versioning is important since everything in master will be pushed to Chrome Store.

**Comment by empeje** [comment]
mas @yuliefas I tried to build this locally but I can't select domain after I input the public key to the short.io options.

**Comment by yuliefas** [comment]
@empeje you can't user public key,
if we use the public key it can only used to create short url but u can't use the public key to get a list of domain, so i changed the public key config to private key
sorry about it and i know it's too risky and not recommended by the documentation. any solution?
ref : https://developers.short.io/reference#apidomainsget

**Comment by empeje** [comment]
Oh using the private key, I think using the private key is okay because the key is only living in the user browser. BTW, still can't work with the private key as well

@yuliefas

**Comment by yuliefas** [comment]
in my chrome browser it works fine
and i just run build normally, yarn run build and it works fine.
what's the error message? can you check and paste it here?

**Comment by yuliefas** [comment]
in my chrome browser it works fine
and i just run build normally, yarn run build and it works fine.

where you get the screenshoot of the error message?
in extension or normal browser page
because chrome.storage.sync only run in extension

**Comment by yuliefas** [comment]
> mas @yuliefas I tried to build this locally but I can't select domain after I input the public key to the short.io options.
> 
> Screen Shot 2020-10-19 at 11 36 39

sorry i missed the screenshot
chrome.storage.sync can not use in normal page browser, chrome.storage only can use in extension
@empeje

**Comment by yuliefas** [comment]
normal window browser page
Screen Shot 2020-10-19 at 13 12 59

extension browser page
Screen Shot 2020-10-19 at 13 12 54

if you want, i can change the chrome.storage to window.localStorage

**Comment by empeje** [comment]
Hi mas @yuliefas I can confirm now that the feature works, however

1. the domain select box still disable after I input the secret key
2. please explicitly tell the user that it is secret key, not a public API key
3. I think you can make the domain selection in as a select box not a modal, it is confusing because I should click the domain select box that greyed out.


Screen Shot 2020-10-19 at 13 19 16

**Comment by yuliefas** [comment]
oke mas @empeje i will change to drop down and thats better haha

**Comment by yuliefas** [comment]
> Hi mas @yuliefas I can confirm now that the feature works, however
> 
> 1. the domain select box still disable after I input the secret key
> 2. please explicitly tell the user that it is secret key, not a public API key
> 3. I think you can make the domain selection in as a select box not a modal, it is confusing because I should click the domain select box that greyed out.
> 
> Screen Shot 2020-10-19 at 13 19 16


Hi mas @empeje i will update to this.
Screen Shot 2020-10-19 at 15 08 29

**Comment by empeje** [comment]
Looks good now mas @yuliefas

**Review by empeje — APPROVED** [review]

**Review by empeje — APPROVED** [review]

**Pull request merged**
